server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  web:
    resources:
      # spring 静态资源扫描路径
      static-locations: classpath:/static/
  freemarker:
    #指定freemarker的模板路径和模板的后缀
    template-loader-path: classpath:/webapp/
    suffix: .ftl
    # 指定字符集
    charset: utf-8
    # 指定是否要启用缓存
    cache: false
    #指定是否要暴露请求和会话属性
    expose-request-attributes: true
    expose-session-attributes: true